version: '2'
services:
  amor: #Main
    build: .
    links:
      - mongo
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  heimdall:
    image: "heimdall:dev"
    links:
     - mongo
    environment:
      NODE_ENV: 'development'
      KAFKA_HOST: "kafka"
      ZOOKEEPER_PORT: 2181
    ports:
      - 8001:8000

#  redis:
#    image: "redis:alpine"

  mongo:
    image: "mongo:latest"
    volumes:
      - ./resources/data/db:/data/db
      - ./resources/backup:/var/mongodb/backup
    ports:
       - 27017:27017
#
#  kafka:
#    image: spotify/kafka
#    environment:
#      ADVERTISED_HOST: kafka
#      ADVERTISED_PORT: 9092
#    ports:
#      - 2181:2181 # Zookeeper
#      - 9092:9092 # Kafka
